// address: 0x80489f0
int main(int argc, char* argv[], char** envp) {
    int local0; 		// r29
    int local1; 		// r24
    int local3; 		// r0
    int local4; 		// tmp1
    short local5; 		// tmph

    %esp = %esp - 4;
    *(int*)%esp = local0;
    local0 = %esp;
    local4 = %esp;
    %esp = %esp - 0xc98;
    local4 = *(int*)(local0 + 8) - 3;
    if (%flags) {
        local4 = %esp;
        %esp = %esp - 4;
        %esp = %esp - 4;
        *(int*)%esp = 20;
        local1 = *(int*)(local0 + 12);
        local4 = local1;
        local1 += 4;
        %esp = %esp - 4;
        *(int*)%esp = *(int*)local1;
        local1 = local0 - 0xc88;
        %esp = %esp - 4;
        *(int*)%esp = local1;
        %esp = %esp - 4;
        strncpy();
        local4 = %esp;
        %esp += 16;
        local4 = %esp;
        %esp = %esp - 4;
        %esp = %esp - 4;
        *(int*)%esp = 1024;
        local1 = *(int*)(local0 + 12);
        local4 = local1;
        local1 += 8;
        %esp = %esp - 4;
        *(int*)%esp = *(int*)local1;
        local1 = local0 - 0xc68;
        %esp = %esp - 4;
        *(int*)%esp = local1;
        %esp = %esp - 4;
        strncpy();
        local4 = %esp;
        %esp += 16;
        local4 = %esp;
        %esp = %esp - 8;
        %esp = %esp - 4;
        *(int*)%esp = 0x8048f3f;
        local1 = local0 - 0xc68;
        %esp = %esp - 4;
        *(int*)%esp = local1;
        %esp = %esp - 4;
        fopen();
        local4 = %esp;
        %esp += 16;
        local1 = local1;
        *(int*)(local0 - 0xc8c) = local1;
        local4 = *(int*)(local0 - 0xc8c);
        if (%flags) {
            local4 = %esp;
            %esp = %esp - 4;
            %esp = %esp - 4;
            *(int*)%esp = 0x804;
            %esp = %esp - 4;
            *(int*)%esp = 0;
            local1 = local0 - 0x828;
            %esp = %esp - 4;
            *(int*)%esp = local1;
            %esp = %esp - 4;
            memset();
            local4 = %esp;
            %esp += 16;
            local1 = local0 - 0x828;
            local4 = local1;
            local1 += 1044;
            *(int*)(local0 - 16) = local1;
            *(int*)(local0 - 0xc90) = 0;
            do {
                %esp = %esp - 4;
                *(int*)%esp = *(int*)(local0 - 0xc8c);
                %esp = %esp - 4;
                *(int*)%esp = 1;
                %esp = %esp - 4;
                *(int*)%esp = 2;
                local1 = *(int*)(local0 - 0xc90);
                local1 = local1;
                local4 = local1;
                local1 = local1 * 2;
                local4 = local1;
                local1 += *(int*)(local0 - 16);
                local4 = local1;
                local1 += 4;
                %esp = %esp - 4;
                *(int*)%esp = local1;
                %esp = %esp - 4;
                fread();
                local4 = %esp;
                %esp += 16;
                *(int*)(local0 - 0xc94) = local1;
                local4 = *(int*)(local0 - 0xc94);
                if (%flags) {
                    local1 = local0 - 0xc90;
                    local4 = *(int*)local1;
                    *(int*)local1++;
                }
                local4 = *(int*)(local0 - 0xc94);
            } while (%flags);
            local4 = *(int*)(local0 - 0xc90);
            if (%flags) {
                local4 = *(int*)(local0 - 0xc90) - 80;
                if (%flags) {
                    local4 = %esp;
                    %esp = %esp - 12;
                    %esp = %esp - 4;
                    *(int*)%esp = *(int*)(local0 - 0xc8c);
                    %esp = %esp - 4;
                    fclose();
                    local4 = %esp;
                    %esp += 16;
                    *(char*)(local0 - 1060) = 51;
                    *(short*)(local0 - 0x826) = 16;
                    local4 = %esp;
                    %esp = %esp - 8;
                    %esp = %esp - 4;
                    *(int*)%esp = 0x8048f77;
                    local1 = local0 - 0x828;
                    local4 = local1;
                    local1 += 1031;
                    %esp = %esp - 4;
                    *(int*)%esp = local1;
                    %esp = %esp - 4;
                    strcpy();
                    local4 = %esp;
                    %esp += 16;
                    local1 = local0 - 0x826;
                    local5 = *(int*)local1;
                    *(int*)local1 += 168;
                    local4 = %esp;
                    %esp = %esp - 4;
                    %esp = %esp - 4;
                    *(int*)%esp = 2;
                    local1 = local0 - 0x828;
                    local4 = local1;
                    local1 += 2;
                    %esp = %esp - 4;
                    *(int*)%esp = local1;
                    local1 = local0 - 0x828;
                    local4 = local1;
                    local1 += 1029;
                    %esp = %esp - 4;
                    *(int*)%esp = local1;
                    %esp = %esp - 4;
                    memcpy();
                    local4 = %esp;
                    %esp += 16;
                    local4 = %esp;
                    %esp = %esp - 4;
                    %esp = %esp - 4;
                    *(int*)%esp = 0;
                    %esp = %esp - 4;
                    *(int*)%esp = 1;
                    %esp = %esp - 4;
                    *(int*)%esp = 2;
                    %esp = %esp - 4;
                    socket();
                    local4 = %esp;
                    %esp += 16;
                    local1 = local1;
                    *(int*)(local0 - 12) = local1;
                    local4 = *(int*)(local0 - 12) + 1;
                    if (%flags) {
                        local4 = %esp;
                        %esp = %esp - 4;
                        %esp = %esp - 4;
                        *(int*)%esp = 16;
                        %esp = %esp - 4;
                        *(int*)%esp = 0;
                        local1 = local0 - 0x838;
                        %esp = %esp - 4;
                        *(int*)%esp = local1;
                        %esp = %esp - 4;
                        memset();
                        local4 = %esp;
                        %esp += 16;
                        *(short*)(local0 - 0x838) = 2;
                        local4 = %esp;
                        %esp = %esp - 12;
                        %esp = %esp - 4;
                        *(int*)%esp = 0;
                        %esp = %esp - 4;
                        htonl();
                        local4 = %esp;
                        %esp += 16;
                        local1 = local1;
                        local1 = local1;
                        *(int*)(local0 - 0x834) = local1;
                        local4 = %esp;
                        %esp = %esp - 12;
                        %esp = %esp - 4;
                        *(int*)%esp = 0;
                        %esp = %esp - 4;
                        htons();
                        local4 = %esp;
                        %esp += 16;
                        local1 = local1;
                        local1 = local1;
                        *(int*)(local0 - 0x836) = local3;
                        local4 = %esp;
                        %esp = %esp - 4;
                        %esp = %esp - 4;
                        *(int*)%esp = 16;
                        local1 = local0 - 0x838;
                        %esp = %esp - 4;
                        *(int*)%esp = local1;
                        %esp = %esp - 4;
                        *(int*)%esp = *(int*)(local0 - 12);
                        %esp = %esp - 4;
                        bind();
                        local4 = %esp;
                        %esp += 16;
                        local1 = local1;
                        local4 = local1 + 1;
                        if (%flags) {
                            local4 = %esp;
                            %esp = %esp - 4;
                            %esp = %esp - 4;
                            *(int*)%esp = 16;
                            %esp = %esp - 4;
                            *(int*)%esp = 0;
                            local1 = local0 - 0x848;
                            %esp = %esp - 4;
                            *(int*)%esp = local1;
                            %esp = %esp - 4;
                            memset();
                            local4 = %esp;
                            %esp += 16;
                            *(short*)(local0 - 0x848) = 2;
                            local4 = %esp;
                            %esp = %esp - 12;
                            local1 = local0 - 0xc88;
                            %esp = %esp - 4;
                            *(int*)%esp = local1;
                            %esp = %esp - 4;
                            inet_addr();
                            local4 = %esp;
                            %esp += 16;
                            local1 = local1;
                            *(int*)(local0 - 0x844) = local1;
                            local4 = %esp;
                            %esp = %esp - 12;
                            %esp = %esp - 4;
                            *(int*)%esp = 0x22b8;
                            %esp = %esp - 4;
                            htons();
                            local4 = %esp;
                            %esp += 16;
                            local1 = local1;
                            local1 = local1;
                            *(int*)(local0 - 0x846) = local3;
                            local4 = %esp;
                            %esp = %esp - 8;
                            local1 = local0 - 0xc88;
                            %esp = %esp - 4;
                            *(int*)%esp = local1;
                            %esp = %esp - 4;
                            *(int*)%esp = 0x8048f7f;
                            %esp = %esp - 4;
                            printf();
                            local4 = %esp;
                            %esp += 16;
                            local4 = %esp;
                            %esp = %esp - 4;
                            %esp = %esp - 4;
                            *(int*)%esp = 16;
                            local1 = local0 - 0x848;
                            %esp = %esp - 4;
                            *(int*)%esp = local1;
                            %esp = %esp - 4;
                            *(int*)%esp = *(int*)(local0 - 12);
                            %esp = %esp - 4;
                            connect();
                            local4 = %esp;
                            %esp += 16;
                            local1 = local1;
                            local4 = local1 + 1;
                            if (%flags) {
                                local4 = %esp;
                                %esp = %esp - 8;
                                local1 = local0 - 0xc68;
                                %esp = %esp - 4;
                                *(int*)%esp = local1;
                                %esp = %esp - 4;
                                *(int*)%esp = 0x8048f9a;
                                %esp = %esp - 4;
                                printf();
                                local4 = %esp;
                                %esp += 16;
                                %esp = %esp - 4;
                                *(int*)%esp = 0;
                                local1 = (*(int*)(local0 - 0x826));
                                %esp = %esp - 4;
                                *(int*)%esp = local1;
                                local1 = local0 - 0x828;
                                local4 = local1;
                                local1 += 1028;
                                %esp = %esp - 4;
                                *(int*)%esp = local1;
                                %esp = %esp - 4;
                                *(int*)%esp = *(int*)(local0 - 12);
                                %esp = %esp - 4;
                                send();
                                local4 = %esp;
                                %esp += 16;
                                local1 = local1;
                                local4 = local1 + 1;
                                if (%flags) {
                                    %esp = %esp - 4;
                                    *(int*)%esp = 0;
                                    %esp = %esp - 4;
                                    *(int*)%esp = 3;
                                    local1 = local0 - 0x858;
                                    %esp = %esp - 4;
                                    *(int*)%esp = local1;
                                    %esp = %esp - 4;
                                    *(int*)%esp = *(int*)(local0 - 12);
                                    %esp = %esp - 4;
                                    recv();
                                    local4 = %esp;
                                    %esp += 16;
                                    local1 = local1;
                                    local4 = local1 + 1;
                                    if (%flags) {
                                        local4 = %esp;
                                        %esp = %esp - 4;
                                        %esp = %esp - 4;
                                        *(int*)%esp = 2;
                                        local1 = local0 - 0x858;
                                        local4 = local1;
                                        local1++;
                                        %esp = %esp - 4;
                                        *(int*)%esp = local1;
                                        local1 = local0 - 0x85a;
                                        %esp = %esp - 4;
                                        *(int*)%esp = local1;
                                        %esp = %esp - 4;
                                        memcpy();
                                        local4 = %esp;
                                        %esp += 16;
                                        local5 = *(int*)(local0 - 0x85a);
                                        if (%flags) {
L5:
                                            %esp = %esp - 4;
                                            *(int*)%esp = 0;
                                            local1 = (*(int*)(local0 - 0x85a));
                                            %esp = %esp - 4;
                                            *(int*)%esp = local1;
                                            local1 = local0 - 0x828;
                                            local4 = local1;
                                            local1 += 4;
                                            %esp = %esp - 4;
                                            *(int*)%esp = local1;
                                            %esp = %esp - 4;
                                            *(int*)%esp = *(int*)(local0 - 12);
                                            %esp = %esp - 4;
                                            recv();
                                            local4 = %esp;
                                            %esp += 16;
                                            local4 = %esp;
                                            %esp = %esp - 8;
                                            %esp = %esp - 4;
                                            *(int*)%esp = 1;
                                            %esp = %esp - 4;
                                            *(int*)%esp = *(int*)(local0 - 12);
                                            %esp = %esp - 4;
                                            shutdown();
                                            local4 = %esp;
                                            %esp += 16;
                                            local4 = %esp;
                                            %esp = %esp - 12;
                                            %esp = %esp - 4;
                                            *(int*)%esp = *(int*)(local0 - 12);
                                            %esp = %esp - 4;
                                            close();
                                            local4 = %esp;
                                            %esp += 16;
                                            local4 = %esp;
                                            %esp = %esp - 12;
                                            %esp = %esp - 4;
                                            *(int*)%esp = 0x8048fad;
                                            %esp = %esp - 4;
                                            printf();
                                            local4 = %esp;
                                            %esp += 16;
                                            local1 = 1;
                                        } else {
                                            local5 = *(int*)(local0 - 0x85a) - 1024;
                                            if (%flags) {
                                                goto L5;
                                            } else {
                                                local4 = %esp;
                                                %esp = %esp - 8;
                                                %esp = %esp - 4;
                                                *(int*)%esp = 1;
                                                %esp = %esp - 4;
                                                *(int*)%esp = *(int*)(local0 - 12);
                                                %esp = %esp - 4;
                                                shutdown();
                                                local4 = %esp;
                                                %esp += 16;
                                                local4 = %esp;
                                                %esp = %esp - 12;
                                                %esp = %esp - 4;
                                                *(int*)%esp = *(int*)(local0 - 12);
                                                %esp = %esp - 4;
                                                close();
                                                local4 = %esp;
                                                %esp += 16;
                                                local1 = -1;
                                            }
                                        }
                                    } else {
                                        local4 = %esp;
                                        %esp = %esp - 12;
                                        %esp = %esp - 4;
                                        *(int*)%esp = *(int*)(local0 - 12);
                                        %esp = %esp - 4;
                                        close();
                                        local4 = %esp;
                                        %esp += 16;
                                        local1 = -1;
                                    }
                                } else {
                                    local4 = %esp;
                                    %esp = %esp - 12;
                                    %esp = %esp - 4;
                                    *(int*)%esp = *(int*)(local0 - 12);
                                    %esp = %esp - 4;
                                    close();
                                    local4 = %esp;
                                    %esp += 16;
                                    local1 = -1;
                                }
                            } else {
                                local4 = %esp;
                                %esp = %esp - 12;
                                %esp = %esp - 4;
                                *(int*)%esp = *(int*)(local0 - 12);
                                %esp = %esp - 4;
                                close();
                                local4 = %esp;
                                %esp += 16;
                                local1 = -1;
                            }
                        } else {
                            local4 = %esp;
                            %esp = %esp - 12;
                            %esp = %esp - 4;
                            *(int*)%esp = *(int*)(local0 - 12);
                            %esp = %esp - 4;
                            close();
                            local4 = %esp;
                            %esp += 16;
                            local1 = -1;
                        }
                    } else {
                        local1 = -1;
                    }
                } else {
                    local4 = %esp;
                    %esp = %esp - 8;
                    %esp = %esp - 4;
                    *(int*)%esp = 0x8048f67;
                    %esp = %esp - 4;
                    *(int*)%esp = *(int*)0x804a150;
                    %esp = %esp - 4;
                    fprintf();
                    local4 = %esp;
                    %esp += 16;
                    local4 = %esp;
                    %esp = %esp - 12;
                    %esp = %esp - 4;
                    *(int*)%esp = *(int*)(local0 - 0xc8c);
                    %esp = %esp - 4;
                    fclose();
                    local4 = %esp;
                    %esp += 16;
                    local1 = 1;
                }
            } else {
                local4 = %esp;
                %esp = %esp - 8;
                %esp = %esp - 4;
                *(int*)%esp = 0x8048f56;
                %esp = %esp - 4;
                *(int*)%esp = *(int*)0x804a150;
                %esp = %esp - 4;
                fprintf();
                local4 = %esp;
                %esp += 16;
                local4 = %esp;
                %esp = %esp - 12;
                %esp = %esp - 4;
                *(int*)%esp = *(int*)(local0 - 0xc8c);
                %esp = %esp - 4;
                fclose();
                local4 = %esp;
                %esp += 16;
                local1 = 1;
            }
        } else {
            local4 = %esp;
            %esp = %esp - 4;
            local1 = local0 - 0xc68;
            %esp = %esp - 4;
            *(int*)%esp = local1;
            %esp = %esp - 4;
            *(int*)%esp = 0x8048f41;
            %esp = %esp - 4;
            *(int*)%esp = *(int*)0x804a150;
            %esp = %esp - 4;
            fprintf();
            local4 = %esp;
            %esp += 16;
            local1 = 0;
        }
    } else {
        local4 = %esp;
        %esp = %esp - 4;
        %esp = %esp - 4;
        *(int*)%esp = *(int*)(local0 + 8);
        %esp = %esp - 4;
        *(int*)%esp = 0x8048f20;
        %esp = %esp - 4;
        *(int*)%esp = *(int*)0x804a150;
        %esp = %esp - 4;
        fprintf();
        local4 = %esp;
        %esp += 16;
        local1 = 0;
    }
    %esp = local0;
    local0 = *(int*)%esp;
    %esp += 4;
    %esp += 4;
    return;
}

